server:
  port: 8080
  tomcat:
    uri-encoding: utf-8
    max-threads: 10000
  servlet:
    context-path: /healer
    session:
      timeout: 30m

spring:
  freemarker:
    allow-request-override: false
    cache: true
    check-template-location: true
    charset: UTF-8
    content-type: text/html
    expose-request-attributes: false
    expose-spring-macro-helpers: false
    expose-session-attributes: false
    suffix: .html
    template-loader-path: classpath:/templates/
    request-context-attribute:
    prefix:
  datasource:
    url: jdbc:mysql://120.77.171.82:3306/healer?characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  mvc:
    favicon:
      enabled: false